name: GitHub Readme Stats
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * */1 # Every day of the week
jobs:
  stats-tokyonight:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Stats Card
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Stats
        uses: ./.github/actions/github-readme-stats
        id: generate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: 'username=${{ github.repository_owner }}&show_icons=true&count_private=true&line_height=28&hide_border=true&card_width=347&include_all_commits=true&role=owner,collaborator&show=reviews,discussions_answered&rank_icon=percentile&theme=tokyonight'
          path: stats-tokyonight.svg
      - uses: actions/upload-artifact@master
        with:
          name: stats-tokyonight
          path: stats-tokyonight.svg
  top-langs-tokyonight:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Top Languages Card
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Top Languages
        uses: ./.github/actions/github-readme-stats
        id: generate
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          options: 'username=${{ github.repository_owner }}&layout=compact&langs_count=12&hide_border=true&role=owner,collaborator&theme=tokyonight'
          card: top-langs
          path: top-langs-tokyonight.svg
      - uses: actions/upload-artifact@master
        with:
          name: top-langs-tokyonight
          path: top-langs-tokyonight.svg
  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push
    needs: [stats-tokyonight, top-langs-tokyonight]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: stats-tokyonight
          path: grs
      - uses: actions/download-artifact@master
        with:
          name: top-langs-tokyonight
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: grs
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
